export const JOBS = {
    AC_TAGS: "AC_TAGS",
    STICKY_ORDER_CUSTOM_FIELDS: "STICKY_ORDER_CUSTOM_FIELDS",
    STICKY_PROSPECT_CUSTOM_FIELDS: "STICKY_PROSPECT_CUSTOM_FIELDS",
    AC_UPDATE_LIST: "AC_UPDATE_LIST"
}


export const JobType = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED"
}