export const JOBS = {
    /*AC_TAGS: "AC_TAGS",
    STICKY_ORDER_CUSTOM_FIELDS: "STICKY_ORDER_CUSTOM_FIELDS",
    STICKY_PROSPECT_CUSTOM_FIELDS: "STICKY_PROSPECT_CUSTOM_FIELDS",
    AC_UPDATE_LIST: "AC_UPDATE_LIST",*/
    PAGE_VISIT: "PAGE_VISIT",
    PAGE_CLICK: "PAGE_CLICK",
    SIGNUP: "SIGNUP",
    SALE: "SALE",
    UPSELL_SALE:"UPSELL_SALE",
    FAILED_SALE: "FAILED_SALE",
    FAILED_UPSELL_SALE: "FAILED_UPSELL_SALE",
    ERROR: "ERROR",
}


export const JobType = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED"
}